table vw_Calendar
	lineageTag: d76ff648-9257-4060-aa5e-9b6ac7b8ba5d

	column Calendar_Key
		dataType: string
		lineageTag: 89da625c-daf4-4b68-8cab-be71406e17c2
		summarizeBy: none
		sourceColumn: Calendar_Key

		annotation SummarizationSetBy = Automatic

	column CalendarMonthKey
		dataType: int64
		formatString: 0
		lineageTag: df0826ce-bf62-4904-abfb-981b15ea5a73
		summarizeBy: count
		sourceColumn: CalendarMonthKey

		annotation SummarizationSetBy = Automatic

	column Calendar_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: b247cffc-6631-43b8-b8f7-f0635fb4b749
		summarizeBy: none
		sourceColumn: Calendar_Date

		variation Variation
			isDefault
			relationship: a1ab48dd-647f-46d6-82a3-36a29502652b
			defaultHierarchy: LocalDateTable_67b269d6-46c4-4cdd-ba9d-df1530638308.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column CalendarDateName
		dataType: string
		lineageTag: 1140ce14-9140-436a-af16-5d87c0dc5e35
		summarizeBy: none
		sourceColumn: CalendarDateName

		annotation SummarizationSetBy = Automatic

	column Day_of_Month
		dataType: int64
		formatString: 0
		lineageTag: 97218d53-2fce-47bf-ae7d-e5b8cedf6440
		summarizeBy: sum
		sourceColumn: Day_of_Month

		annotation SummarizationSetBy = Automatic

	column Month_of_Year
		dataType: int64
		formatString: 0
		lineageTag: e1d98f1d-6466-40ea-83a0-c0c0f92c1f09
		summarizeBy: sum
		sourceColumn: Month_of_Year

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: d0320b72-eeb3-4d73-883a-9c8c8a56e64b
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 5c9f1673-2a0b-4fd2-b20b-243145990a33
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column QuarterName
		dataType: string
		lineageTag: 0c8dba14-9dde-4193-bba3-f4b2f8b5f96f
		summarizeBy: none
		sourceColumn: QuarterName

		annotation SummarizationSetBy = Automatic

	column Half_of_Year
		dataType: int64
		formatString: 0
		lineageTag: ead9b506-f3f8-4320-b31d-e1e1041d4f85
		summarizeBy: sum
		sourceColumn: Half_of_Year

		annotation SummarizationSetBy = Automatic

	column HalfYearName
		dataType: string
		lineageTag: 73c4bee0-1736-41c8-aa80-557ecc929e87
		summarizeBy: none
		sourceColumn: HalfYearName

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 4201194c-a604-4970-9603-f6313deb0237
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column YearName
		dataType: string
		lineageTag: 21c6f76e-740b-4020-a29a-4f1cb7967011
		summarizeBy: none
		sourceColumn: YearName

		annotation SummarizationSetBy = Automatic

	column IsBusinessDay
		dataType: int64
		formatString: 0
		lineageTag: 1f88fac3-3332-45b6-bd7a-8619170b6d8f
		summarizeBy: sum
		sourceColumn: IsBusinessDay

		annotation SummarizationSetBy = Automatic

	column FiscalYearMonth
		dataType: int64
		formatString: 0
		lineageTag: d6f32ca7-2cf2-4911-ad6f-873fc7a41566
		summarizeBy: sum
		sourceColumn: FiscalYearMonth

		annotation SummarizationSetBy = Automatic

	column FiscalMonth
		dataType: int64
		formatString: 0
		lineageTag: cc5dc514-e3b5-4f2d-b7b2-7d33bbd79775
		summarizeBy: sum
		sourceColumn: FiscalMonth

		annotation SummarizationSetBy = Automatic

	column FiscalMonthName
		dataType: string
		lineageTag: e009428e-79d8-47e7-a739-b2f4f1e7a633
		summarizeBy: none
		sourceColumn: FiscalMonthName

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterName
		dataType: string
		lineageTag: 4a238500-1ede-482c-879e-4de9ffaea921
		summarizeBy: none
		sourceColumn: FiscalQuarterName

		annotation SummarizationSetBy = Automatic

	column FiscalQuarter
		dataType: int64
		formatString: 0
		lineageTag: bf9d3d57-6900-4b59-bfa5-b6ba260161d6
		summarizeBy: sum
		sourceColumn: FiscalQuarter

		annotation SummarizationSetBy = Automatic

	column FiscalHalf
		dataType: int64
		formatString: 0
		lineageTag: 460dc6de-3761-41b1-ab88-213271b5a575
		summarizeBy: sum
		sourceColumn: FiscalHalf

		annotation SummarizationSetBy = Automatic

	column FiscalHalfName
		dataType: string
		lineageTag: d7623375-b361-458e-b930-d9277988268f
		summarizeBy: none
		sourceColumn: FiscalHalfName

		annotation SummarizationSetBy = Automatic

	column FiscalYear
		dataType: int64
		formatString: 0
		lineageTag: 3b6bd6d9-84ab-44e1-b952-7d6c1dd81e31
		summarizeBy: sum
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column FiscalYearName
		dataType: string
		lineageTag: 3feea2a6-70e5-4777-ba10-25bb7948e40b
		summarizeBy: none
		sourceColumn: FiscalYearName

		annotation SummarizationSetBy = Automatic

	column FiscalBusinessDayOfMonth
		dataType: int64
		formatString: 0
		lineageTag: 810b35ec-aea5-4125-ba76-f3d5578d619f
		summarizeBy: sum
		sourceColumn: FiscalBusinessDayOfMonth

		annotation SummarizationSetBy = Automatic

	column YMD-text
		dataType: string
		lineageTag: f26023ce-0749-466d-8288-24b49e748bea
		summarizeBy: none
		sourceColumn: YMD-text

		annotation SummarizationSetBy = Automatic

	column YMD-number
		dataType: dateTime
		formatString: Long Date
		lineageTag: 80295497-fa90-4c59-93a4-67b0e5462519
		summarizeBy: none
		sourceColumn: YMD-number

		variation Variation
			isDefault
			relationship: 228984ff-80f3-4c68-9e85-37dafd7736c8
			defaultHierarchy: LocalDateTable_c42e3d4e-3fcd-4905-aed1-992dea993f65.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column YYYYMM-text
		dataType: string
		lineageTag: eb5b5e78-147d-4151-a464-1a4dd3966445
		summarizeBy: none
		sourceColumn: YYYYMM-text

		annotation SummarizationSetBy = Automatic

	column YYYYMM-Num
		dataType: int64
		formatString: 0
		lineageTag: 45f32692-941b-4eab-b656-e5475d100b24
		summarizeBy: sum
		sourceColumn: YYYYMM-Num

		annotation SummarizationSetBy = Automatic

	column Year_C
		dataType: string
		lineageTag: fbb04549-3e1a-482f-9e12-0bb5e247bac1
		summarizeBy: none
		sourceColumn: Year_C

		annotation SummarizationSetBy = Automatic

	column Dimension-Date = Calendar(FIRSTDATE(vwfactSalesDashboardRev[Calendar_Key]),LASTDATE(vwfactSalesDashboardRev[Calendar_Key]))
		formatString: General Date
		lineageTag: 636803f4-0896-4ee8-aa50-492e1de62a61
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 0d49e369-d954-4b64-a8ce-00d242bcff4e
			defaultHierarchy: LocalDateTable_e9f85ca7-d48b-4af6-a7f1-75067e1aaef9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Week =
			
			WEEKNUM
			(vw_Calendar[Calendar_Date])
		formatString: 0
		lineageTag: 20bd0d3f-4695-42d5-ae81-b465f1a7c652
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition vw_Calendar = m
		mode: import
		source =
				let
				    Source = Sql.Database("TYCNM7BIP1.CORP.TCC.INET", "EnterpriseData"),
				    dbo_vw_Calendar = Source{[Schema="dbo",Item="vw_Calendar"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_vw_Calendar,{{"Calendar_Key", type text}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "Calendar_Key", "Calendar_Key - Copy"),
				    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"Calendar_Key - Copy", "YMD-text"}}),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Renamed Columns", "Calendar_Date", "Calendar_Date - Copy"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Duplicated Column1",{{"Calendar_Date - Copy", type date}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type1",{{"Calendar_Date - Copy", "YMD-number"}}),
				    #"Duplicated Column2" = Table.DuplicateColumn(#"Renamed Columns1", "FiscalYearMonth", "FiscalYearMonth - Copy"),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Duplicated Column2",{{"FiscalYearMonth - Copy", type text}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type2",{{"FiscalYearMonth - Copy", "YYYYMM-text"}}),
				    #"Duplicated Column3" = Table.DuplicateColumn(#"Renamed Columns2", "FiscalYearMonth", "FiscalYearMonth - Copy"),
				    #"Renamed Columns3" = Table.RenameColumns(#"Duplicated Column3",{{"FiscalYearMonth - Copy", "YYYYMM-Num"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns3", "Year_C", each if Date.IsInCurrentYear([Calendar_Date]) then "Current Year" else [Year]),
				    #"Filtered Rows1" = Table.SelectRows(#"Added Custom", each [Calendar_Date] <= DateTime.LocalNow())
				in
				    #"Filtered Rows1"

	annotation PBI_ResultType = Table

