table vwdimSalesOrg
	lineageTag: 929fb46e-eba1-47f2-83b2-309ea25dc73d

	column SalesOrgKey
		dataType: int64
		formatString: 0
		lineageTag: 261e28fe-cb04-4a83-96be-cce9fa993554
		summarizeBy: none
		sourceColumn: SalesOrgKey

		annotation SummarizationSetBy = Automatic

	column Business_Unit_Code
		dataType: string
		lineageTag: dd9884a1-8c84-4283-a000-1d94cfdfffb0
		summarizeBy: none
		sourceColumn: Business_Unit_Code

		annotation SummarizationSetBy = Automatic

	column CompanyCode
		dataType: string
		lineageTag: 6d91061c-1649-4bfb-9e36-cd93e666d110
		summarizeBy: none
		sourceColumn: CompanyCode

		annotation SummarizationSetBy = Automatic

	column CompanyName
		dataType: string
		lineageTag: 93ecc4a5-dfc9-4ef9-8dd1-e187e0f25e12
		summarizeBy: none
		sourceColumn: CompanyName

		annotation SummarizationSetBy = Automatic

	column DivisionCode
		dataType: string
		lineageTag: abdee7a5-03ec-4fed-bcfe-adc1a57725b9
		summarizeBy: none
		sourceColumn: DivisionCode

		annotation SummarizationSetBy = Automatic

	column DivisionName
		dataType: string
		lineageTag: cfac2b2d-fb3b-493b-bb76-d298713deef3
		summarizeBy: none
		sourceColumn: DivisionName

		annotation SummarizationSetBy = Automatic

	column RegionCode
		dataType: string
		lineageTag: 359b2ed1-76ba-408a-a87f-b0c09d14b04a
		summarizeBy: none
		sourceColumn: RegionCode

		annotation SummarizationSetBy = Automatic

	column RegionName
		dataType: string
		lineageTag: 918b593d-afc7-4cc2-a7ff-ce11877aa78f
		summarizeBy: none
		sourceColumn: RegionName

		annotation SummarizationSetBy = Automatic

	column SalesRepName
		dataType: string
		lineageTag: 36d12c76-d47f-4010-b161-e0a20c9ca571
		summarizeBy: none
		sourceColumn: SalesRepName

		annotation SummarizationSetBy = Automatic

	column BuyingGroup
		dataType: string
		lineageTag: e47559c7-d565-4512-998e-d87e06b199d6
		summarizeBy: none
		sourceColumn: BuyingGroup

		annotation SummarizationSetBy = Automatic

	column CustomerNumber
		dataType: string
		lineageTag: 859c6087-dade-4000-b91b-07c29711fe98
		summarizeBy: none
		sourceColumn: CustomerNumber

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: 6bae1e04-ac20-4b0d-95a8-8a6efdf6f5c3
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column VerticalMarket
		dataType: string
		lineageTag: 63616364-2817-414f-a1ea-9ea8382bbae8
		summarizeBy: none
		sourceColumn: VerticalMarket

		annotation SummarizationSetBy = Automatic

	column SalesRepPrimary
		dataType: string
		lineageTag: 0c1c88ea-690f-4477-872d-5951199ad265
		summarizeBy: none
		sourceColumn: SalesRepPrimary

		annotation SummarizationSetBy = Automatic

	column SalesRepSplitPercent
		dataType: double
		lineageTag: 2e11efd4-5d62-45ce-8b78-d8237d30125a
		summarizeBy: sum
		sourceColumn: SalesRepSplitPercent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SalesRepID_Synygy
		dataType: int64
		formatString: 0
		lineageTag: cb99b0de-1b5a-4f0e-ba43-fc40655db638
		summarizeBy: sum
		sourceColumn: SalesRepID_Synygy

		annotation SummarizationSetBy = Automatic

	column SourceCustomerNumber
		dataType: string
		lineageTag: a31bd7a9-34e8-4524-98d9-513f9ccc1d7c
		summarizeBy: none
		sourceColumn: SourceCustomerNumber

		annotation SummarizationSetBy = Automatic

	column Customer
		dataType: string
		lineageTag: fc846f21-757a-4d72-9dfb-e9db9bd6ceef
		summarizeBy: none
		sourceColumn: Customer

		annotation SummarizationSetBy = Automatic

	column IncludeTIC = IF (vwdimSalesOrg[VerticalMarket] <>"Taylor Intercompany|Taylor Intercompany" && vwdimSalesOrg[VerticalMarket] <>"Taylor Intercompany|Intercompany"  && vwdimSalesOrg[VerticalMarket] <>"Intercompany|Intercompany","Exclude Taylor InterCompany",BLANK())
		lineageTag: d7ee9871-79d1-41c1-bd12-4049a7c26f2e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column SL_Account_Name
		dataType: string
		lineageTag: c50aa8f7-771a-427f-9c84-4b79a01dc52f
		summarizeBy: none
		sourceColumn: SL_Account_Name

		annotation SummarizationSetBy = Automatic

	column SLValue
		dataType: string
		lineageTag: fad0a2b9-9e41-48e1-bc3a-31976afba67d
		summarizeBy: none
		sourceColumn: SLValue

		annotation SummarizationSetBy = Automatic

	column CusJoin
		dataType: string
		lineageTag: e20bc4a1-8387-41c7-94ca-68e849416948
		summarizeBy: none
		sourceColumn: CusJoin

		annotation SummarizationSetBy = Automatic

	column LocationCode_BI
		dataType: string
		lineageTag: 30c044e3-4f33-45c3-8aca-5d21bca2491d
		summarizeBy: none
		sourceColumn: LocationCode_BI

		annotation SummarizationSetBy = Automatic

	column LocationName
		dataType: string
		lineageTag: 1d44433e-b6f4-4c8e-802a-173ab5e1cb9d
		summarizeBy: none
		sourceColumn: LocationName

		annotation SummarizationSetBy = Automatic

	partition vwdimSalesOrg = m
		mode: import
		source =
				let
				    Source = Sql.Database("TYCNM7BIP1.CORP.TCC.INET", "EnterpriseData", [CreateNavigationProperties=false]),
				    dbo_vwdimSalesOrg = Source{[Schema="dbo",Item="vwdimSalesOrg"]}[Data],
				    #"Added Custom" = Table.AddColumn(dbo_vwdimSalesOrg, "SLValue", each [CompanyCode] & "::" & [SourceCustomerNumber] & "::" & Number.ToText([SalesRepID_Synygy])),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"CustomerNumber", type text}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type", "CusJoin", each [CompanyCode] & "::" & [CustomerNumber])
				in
				    #"Added Custom1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

