table vwFactSalesDashboardRev
	lineageTag: 167a84e7-358e-40d5-b216-384e6a3768ba

	measure 'Current Year Rev' = COALESCE(sum(vwFactSalesDashboardRev[TotalRevenue]),BLANK())
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0d52d2a3-dff7-41c7-839f-193ac3a4ee91

	measure 'Last Year Rev' = COALESCE(calculate([Current Year Rev], SAMEPERIODLASTYEAR('vw_Calendar'[YMD-number])),BLANK())
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 10730349-0a06-4e25-82b1-a07c9aceb39f

	measure 'CY - PY Difference' = COALESCE([Current Year Rev] - [Last Year Rev],BLANK())
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: af312493-8152-44b4-943f-2be79df28c38

	measure CY-COST = COALESCE(sum(vwFactSalesDashboardRev[TotalCost]),BLANK())
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 18ddc7c4-489e-4f5b-9534-573cd0e406e0

	measure CY-GM = [Current Year Rev]-[CY-COST]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: affe805e-fe69-4db3-b82e-e506d5b56bc9

	measure 'CY-GM %' = DIVIDE([CY-GM],[Current Year Rev],0)
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: ea5c8a4a-d2b2-4ff3-bfcd-2598244b7f5d

	measure Gross-Margin-Calc_N = COALESCE(SUM(vwFactSalesDashboardRev[GrossMargin]),0)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 90095465-e2c6-4a2d-ba10-e235427c0a6f

	measure 'Last Transaction Date' = max(vwFactSalesDashboardRev[Calendar_Key])
		formatString: General Date
		lineageTag: 21ff27e8-e1a8-4a17-8ac8-fba850ec037f

	measure LY-COST = COALESCE(calculate(sum('vwFactSalesDashboardRev'[TotalCost]), SAMEPERIODLASTYEAR('vw_Calendar'[YMD-number])),BLANK())
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 1ef11d07-fd81-4343-8551-f5f54f0b387d

	measure LY-GM = COALESCE([Last Year Rev]-[LY-COST],BLANK())
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b945e562-9a82-429b-9b9b-861635964741

	measure 'LY-GM %' = DIVIDE([LY-GM],[Last Year Rev],0)
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: e756dbae-bda6-4b53-b007-c8cb6943cd83

	measure 'Last Year Rev_KPI' =
			//COALESCE(calculate([Current Year Rev], SAMEPERIODLASTYEAR('vw_Calendar'[YMD-number])),0)
			VAR __res = CALCULATE([Current Year Rev], SAMEPERIODLASTYEAR('vw_Calendar'[YMD-number]))
			RETURN
			IF(ISBLANK(__res),0,__res)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 2f8019e5-12b7-44c5-865e-f9743ae3f4a8

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Current Year Rev_KPI' =
			
			VAR __res = sum(vwFactSalesDashboardRev[TotalRevenue])
			RETURN
			IF(ISBLANK(__res),0,__res)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 2760c0c8-682e-4945-8f11-c00281681bff

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'LY-GM %_KPI' = COALESCE(DIVIDE([LY-GM],[Last Year Rev],0),0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2668a67a-dc79-4c2a-bee8-865739bdabcb

	measure 'CY-GM %_KPI' = COALESCE( DIVIDE([CY-GM],[Current Year Rev],0),0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0de100da-6498-45ac-859c-1122ec768a97

	measure 'Order Quantity' = SUM(vwFactSalesDashboardRev[OrderQuantity])
		formatString: #,0
		lineageTag: 5616954a-21b0-4c91-9e86-a996a348d1c3

	measure 'Order Quantity Previous Period' =
			
			CALCULATE([Order Quantity], SAMEPERIODLASTYEAR('vw_Calendar'[YMD-number]))
		formatString: #,0
		lineageTag: 9b209be5-e51a-4885-8557-a149d9e6e5d1

	measure 'Order Quantity Diff' = [Order Quantity] - [Order Quantity Previous Period]
		formatString: #,0
		lineageTag: f11ea96d-0c4f-4975-b3f7-0d6aca83ff52

	measure 'CY-GM KPI' = IF(ISBLANK([CY-GM]),0,[CY-GM])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 49d407b1-54ed-46f8-b5d3-26c27ce0707c

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'CY-PY %' =
			IF(
			    ISBLANK([Current Year Rev]) && ISBLANK([Last Year Rev]),
			    BLANK(),
			    COALESCE(DIVIDE([Current Year Rev] - [Last Year Rev], [Last Year Rev], 0),0))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 30aab3db-d651-4c8e-a0bb-7104b2c7195c

	measure 'CY - PY Difference KPI' =
			
			IF(ISBLANK([CY - PY Difference]), "N/A", [CY - PY Difference])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: c63186bd-e36f-4d41-a08b-71939c49c228

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'CY-PY % KPI' =
			
			IF(ISBLANK([CY-PY %]), "N/A", [CY-PY %])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5a894752-02bf-4a79-97be-2da834e832d8

	column BUGroupPresident
		dataType: string
		lineageTag: cd1d70f6-dbf4-49f5-abf3-8dd32a79f355
		summarizeBy: none
		sourceColumn: BUGroupPresident

		annotation SummarizationSetBy = Automatic

	column ReportingChannel
		dataType: string
		lineageTag: 8dcd3e03-b873-4eab-9356-722f81544d24
		summarizeBy: none
		sourceColumn: ReportingChannel

		annotation SummarizationSetBy = Automatic

	column GrossMargin
		dataType: decimal
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2899f41a-4050-45e1-94f9-6abfdf08d6af
		summarizeBy: sum
		sourceColumn: GrossMargin

		annotation SummarizationSetBy = Automatic

	column Invoice_Number
		dataType: string
		lineageTag: 62ff6813-50da-461c-ae1f-43007a99ef18
		summarizeBy: none
		sourceColumn: Invoice_Number

		annotation SummarizationSetBy = Automatic

	column ItemKey
		dataType: int64
		formatString: 0
		lineageTag: 5dd9c9b1-fd4d-43f1-85d3-438e26289f27
		summarizeBy: none
		sourceColumn: ItemKey

		annotation SummarizationSetBy = Automatic

	column LegacySource
		dataType: string
		lineageTag: 81702bb7-bbf3-47fd-a0af-6a3cb5a11877
		summarizeBy: none
		sourceColumn: LegacySource

		annotation SummarizationSetBy = Automatic

	column OrderNumber
		dataType: string
		lineageTag: a396d3c7-840a-4eae-bc6b-b9359d238941
		summarizeBy: none
		sourceColumn: OrderNumber

		annotation SummarizationSetBy = Automatic

	column Product_Type_Key
		dataType: int64
		formatString: 0
		lineageTag: 0ad0e5a2-9d9a-4f3c-8c84-dbaf123fddd1
		summarizeBy: none
		sourceColumn: Product_Type_Key

		annotation SummarizationSetBy = Automatic

	column SalesOrgKey
		dataType: int64
		formatString: 0
		lineageTag: 49644888-d442-4186-829e-9e4fdea8ada4
		summarizeBy: none
		sourceColumn: SalesOrgKey

		annotation SummarizationSetBy = Automatic

	column TotalCost
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 802c3d93-6769-4060-a629-cb1607dfe5dc
		summarizeBy: sum
		sourceColumn: TotalCost

		annotation SummarizationSetBy = Automatic

	column TotalRevenue
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 571ca6e6-def2-418d-80e0-ae9635f11ec3
		summarizeBy: sum
		sourceColumn: TotalRevenue

		annotation SummarizationSetBy = Automatic

	column WarehouseKey
		dataType: int64
		formatString: 0
		lineageTag: 300ffc66-8799-4f0d-a2f6-3230a3ad5c6b
		summarizeBy: none
		sourceColumn: WarehouseKey

		annotation SummarizationSetBy = Automatic

	column PlantKey
		dataType: int64
		formatString: 0
		lineageTag: e9e20df1-78aa-4c7c-857c-b6fdd8bf39ba
		summarizeBy: none
		sourceColumn: PlantKey

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: double
		formatString: #,0
		lineageTag: 4980ca3a-839a-4588-b519-2c243c60b24d
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column Calendar_Key
		dataType: dateTime
		formatString: Long Date
		lineageTag: b36cc4ca-4436-4bb3-b4f4-410b420f4fb7
		summarizeBy: none
		sourceColumn: Calendar_Key

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Legacy SRC' = IF (vwFactSalesDashboardRev[LegacySource] IN {"SRC","TC2","WFO"},vwFactSalesDashboardRev[LegacySource],BLANK())
		lineageTag: dc34c4de-468e-4174-a6d4-47d3a170181f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Trans Date' = FORMAT(vwFactSalesDashboardRev[Calendar_Key],"mm/dd/yyyy")
		lineageTag: 755c31f2-1a43-4f68-9ed1-d3a42ff4e62f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column BillType
		dataType: string
		lineageTag: 6671f063-4dd7-47cb-a8f3-a669e5b6bf6d
		summarizeBy: none
		sourceColumn: BillType

		annotation SummarizationSetBy = Automatic

	column BillTypeName
		dataType: string
		lineageTag: c10ee352-3105-4ea2-ac84-8e5e48d8601d
		summarizeBy: none
		sourceColumn: BillTypeName

		annotation SummarizationSetBy = Automatic

	column 'Product Type' = RELATED(vwdimProduct_Types[Product Type])
		lineageTag: 32d85921-2c64-4ca1-8795-c0677687ff53
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ChargeType
		dataType: int64
		formatString: 0
		lineageTag: 370e82a6-ef5d-48b8-babf-8938deaa60df
		summarizeBy: sum
		sourceColumn: ChargeType

		annotation SummarizationSetBy = Automatic

	column ProfitCenterNum
		dataType: int64
		formatString: 0
		lineageTag: fde2f1c7-a35c-48ea-be29-0698a2c14940
		summarizeBy: sum
		sourceColumn: ProfitCenterNum

		annotation SummarizationSetBy = Automatic

	column ProfitCenterName
		dataType: string
		lineageTag: bb5bc4ab-8c4f-4f48-92c8-310e43749028
		summarizeBy: none
		sourceColumn: ProfitCenterName

		annotation SummarizationSetBy = Automatic

	column Profit_Center = format([ProfitCenterNum],"0") & " : " & [ProfitCenterName]
		lineageTag: 319c5a23-c57b-485a-9190-3689e18e8f68
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition vwFactSalesDashboardRev = m
		mode: import
		source =
				let
				    Source = Sql.Database("TYCNM7BIP1.CORP.TCC.INET", "EnterpriseData", [CreateNavigationProperties=false]),
				    dbo_vwFactSalesDashboardRev = Source{[Schema="dbo",Item="vwFactSalesDashboardRev"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_vwFactSalesDashboardRev,{{"Calendar_Key", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Calendar_Key", "Calendar_Key_T"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Calendar_Key", each Text.Range([Calendar_Key_T],0,4) & "-" & Text.Range([Calendar_Key_T],4,2) & "-" & Text.Range([Calendar_Key_T],6,2)),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Calendar_Key", type date}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"Calendar_Key_T"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

